// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsxozvhebywceaubgrcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzeG96dmhlYnl3Y2VhdWJncmNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDU2MDUsImV4cCI6MjA2MDE4MTYwNX0.ZZV0HkFyaROkRjl8K3zKz52BMUo0YSxn-XXSndQkM6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);